name: clase_10
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc:
  equatable:
  local_auth:
  flutter_credit_card:
  image_picker:
  share_plus:
  share:
  screenshot:
  path_provider:
  flutter_share: ^2.0.0
  image_gallery_saver:
  permission_handler:
  share_plus_web: ^2.0.4
  feature_discovery: ^0.14.1
  shared_preferences_web: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true